### ISSUE TITLE
zero copy for 'sed'

### ISSUE THREAD

**Issue by jreiser** [alexmyczko/autoexec.bat#1]
I post this issue (instead of creating a PullRequest) because GitHub did not allow me to create a branch in this project using my newly-created PersonalAccessToken:
```
$     git push --set-upstream origin jreiser-zerocopy
Username for 'https://github.com': jreiser@BitWagon.com
Password for 'https://jreiser@BitWagon.com@github.com': 
remote: Permission to alexmyczko/autoexec.bat.git denied to jreiser.
fatal: unable to access 'https://github.com/alexmyczko/autoexec.bat.git/': The requested URL returned error: 403
```
Anyway:
```
$ git diff
diff --git a/bashx b/bashx
index ff9cbdf..0f922a6 100644
--- a/bashx
+++ b/bashx
@@ -2,6 +2,6 @@
 # bash compressor
 # upx but for bash scripts only
 echo '#!/bin/sh' > ${1}xz
-echo 'sed 1,2d "$0"|unxz|bash -s -- "$@";exit' >> ${1}xz
-xz -c -9 $1 >> ${1}xz
+echo '(sed -n 2q; exec unxz)<"$0"|bash -s -- "$@";exit' >> ${1}xz
+xz -c -6 $1 >> ${1}xz
 chmod +x ${1}xz
```
The main tweak is for `sed` to quit after positioning the input file (and have `unxz` read the rest of the file directly) instead of `sed` copying the rest of the input into a pipe which then is read by `unxz`.  Secondary tweaks: `unxz` is executed by `/bin/sh` which might not be `bash`, and minimal shells might not implement default tail merging (avoiding `clone`) of the last process in a pipeline; so use `exec` to force the tail merge.  Also, the documentation for `man unxz`says that compression effort `-7` through `-9` are likely a waste of time and RAM, especially for de-compression, where they require 17MB, 33MB, or 65MB instead of only the 9MB for `-6`.

**Comment by alexmyczko** [comment]
Thank you so much. Will apply asap.
